// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgvR2g5yeJwlbhwwEgA0_ZbUWKeGFTpKk',
    appId: '1:10448338651:web:04b1961134299580df16fe',
    messagingSenderId: '10448338651',
    projectId: 'blooddonationapp-a24fe',
    authDomain: 'blooddonationapp-a24fe.firebaseapp.com',
    storageBucket: 'blooddonationapp-a24fe.appspot.com',
    measurementId: 'G-S09CFHM4C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Boh4ujEjjrQ4c6zMEJ-dVajUbGFRcXE',
    appId: '1:10448338651:android:01fd6d83f41aaf71df16fe',
    messagingSenderId: '10448338651',
    projectId: 'blooddonationapp-a24fe',
    storageBucket: 'blooddonationapp-a24fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9h2M2k2C6SWYUk4XJY9ZoVEBI1QjaDUM',
    appId: '1:10448338651:ios:c3d9e51128d0a34ddf16fe',
    messagingSenderId: '10448338651',
    projectId: 'blooddonationapp-a24fe',
    storageBucket: 'blooddonationapp-a24fe.appspot.com',
    iosBundleId: 'com.example.bloodDonorsApp',
  );
}
